import { createElement } from 'lwc';
import Record from 'c/record';
import { CurrentPageReference } from 'lightning/navigation';


const mockCurrentPageReference = require('./data/CurrentPageReference.json');

describe('c-record', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-record', {
            is: Record
        });

        // Act
        document.body.appendChild(element);


        // Select element for validation
        const preElement = element.shadowRoot.querySelector('pre');
        expect(preElement).not.toBeNull();

        CurrentPageReference.emit(mockCurrentPageReference);

        return Promise.resolve().then(() => {
            expect(preElement.textContent).toBe(
                JSON.stringify(mockCurrentPageReference, null, 2)
            );
        });

    });
});